adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: 1246b6d2-8c74-41e7-a301-84a97494bd16
adx_partialurl: Product image 1.png
adx_publishingstateid: 547e212d-2b54-4925-8a63-775b24618e5a
adx_webfileid: c45e1d6e-a0e1-4f24-b5ab-9f58e00667dc
annotationid: 3fca284b-89f7-f011-8406-7ced8d24db72
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: c45e1d6e-a0e1-4f24-b5ab-9f58e00667dc
objecttypecode: adx_webfile
